### ISSUE TITLE
Regarding the 2 sftp server

### ISSUE THREAD

**Issue by krishna710942** [ekim197711/springintegration-sftpmessagehandler#1]
Hi Mike , I have 2 sftp server and i want to copy file from one sftp server to another sftp server how can i do that . and how can i achieve that .

**Comment by ekim197711** [comment]
Download the file.
Then upload the file to 2nd sftp server.

Mvh.
Mike Møller Nielsen
+45 61600005
www.codeinvestigator.com
Code Investigator - part of URSolutions
Cvr: 27503608

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
